-- CareMatch Snowflake platform bootstrap.
-- Run once as ACCOUNTADMIN; daily ingestion uses CAREMATCH_LOADER.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS CAREMATCH_INGEST_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'CareMatch ingestion and development warehouse';

CREATE DATABASE IF NOT EXISTS CAREMATCH
  COMMENT = 'CareMatch modern data stack case study';

CREATE SCHEMA IF NOT EXISTS CAREMATCH.RAW;
CREATE SCHEMA IF NOT EXISTS CAREMATCH.STAGING;
CREATE SCHEMA IF NOT EXISTS CAREMATCH.ANALYTICS;

CREATE ROLE IF NOT EXISTS CAREMATCH_LOADER;
CREATE ROLE IF NOT EXISTS CAREMATCH_TRANSFORMER;
CREATE ROLE IF NOT EXISTS CAREMATCH_ANALYST;

GRANT USAGE ON WAREHOUSE CAREMATCH_INGEST_WH TO ROLE CAREMATCH_LOADER;
GRANT USAGE ON DATABASE CAREMATCH TO ROLE CAREMATCH_LOADER;
GRANT USAGE, CREATE STAGE, CREATE FILE FORMAT, CREATE TABLE
  ON SCHEMA CAREMATCH.RAW TO ROLE CAREMATCH_LOADER;

GRANT USAGE ON WAREHOUSE CAREMATCH_INGEST_WH TO ROLE CAREMATCH_TRANSFORMER;
GRANT USAGE ON DATABASE CAREMATCH TO ROLE CAREMATCH_TRANSFORMER;
GRANT USAGE ON SCHEMA CAREMATCH.RAW TO ROLE CAREMATCH_TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW
  ON SCHEMA CAREMATCH.STAGING TO ROLE CAREMATCH_TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW
  ON SCHEMA CAREMATCH.ANALYTICS TO ROLE CAREMATCH_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA CAREMATCH.RAW TO ROLE CAREMATCH_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CAREMATCH.RAW TO ROLE CAREMATCH_TRANSFORMER;

GRANT USAGE ON WAREHOUSE CAREMATCH_INGEST_WH TO ROLE CAREMATCH_ANALYST;
GRANT USAGE ON DATABASE CAREMATCH TO ROLE CAREMATCH_ANALYST;
GRANT USAGE ON SCHEMA CAREMATCH.ANALYTICS TO ROLE CAREMATCH_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA CAREMATCH.ANALYTICS TO ROLE CAREMATCH_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CAREMATCH.ANALYTICS TO ROLE CAREMATCH_ANALYST;

GRANT ROLE CAREMATCH_LOADER TO ROLE CAREMATCH_TRANSFORMER;
GRANT ROLE CAREMATCH_LOADER TO USER YASEEN;
GRANT ROLE CAREMATCH_TRANSFORMER TO USER YASEEN;
GRANT ROLE CAREMATCH_ANALYST TO USER YASEEN;

CREATE STORAGE INTEGRATION IF NOT EXISTS CAREMATCH_S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::237657481511:role/carematch-dev-snowflake-s3'
  STORAGE_ALLOWED_LOCATIONS = ('s3://carematch-data-237657481511-dev/raw/');

GRANT USAGE ON INTEGRATION CAREMATCH_S3_INT TO ROLE CAREMATCH_LOADER;

DESC INTEGRATION CAREMATCH_S3_INT;
